### ISSUE TITLE
unsafe:chrome-extension ? (v3.21.24)

### ISSUE THREAD

**Issue by repsorp** [kvhnuke/etherwallet#1936]
chromium Version 68.0.3440.75 (Build officiel) Built on Ubuntu , running on Ubuntu 16.04 (64 bits)

Clicking on "My Wallet" or "Add Wallet" in chrome-extension-v3.21.19
![capture du 2018-06-29 13-37-05](https://user-images.githubusercontent.com/6297032/42090971-cd60a53c-7ba3-11e8-8f52-098a1df31e90.png)
get me to a blank page (new tab) with the following message:
![capture du 2018-06-29 13-38-57](https://user-images.githubusercontent.com/6297032/42090955-bfd46fe8-7ba3-11e8-832e-240a301e2533.png)

Works if I remove "unsafe:" 
chrome-extension://hnilhihegimhabmheeajlhlpoibhabhn/cx-wallet.html#my-wallet

Some icons are missing though
![capture du 2018-06-29 13-41-30](https://user-images.githubusercontent.com/6297032/42090996-e945296c-7ba3-11e8-9382-88175ca59bd2.png)
![capture du 2018-06-29 13-58-13](https://user-images.githubusercontent.com/6297032/42091164-8156a960-7ba4-11e8-942e-ce03dcbd8031.png)
![capture du 2018-06-29 14-03-01](https://user-images.githubusercontent.com/6297032/42091309-348d3224-7ba5-11e8-9844-3525af7491c3.png)

===

Error in response to tabs.query: TypeError: Cannot read property 'url' of undefined
Context
_generated_background_page.html
Stack Trace
background/extension.js:47 (whitelisted.domains.find.dom)
background/extension.js:46 (querycB)
background/extension.js:18 (Object.callback)
background/extension.js:17 (anonymous function)
background/extension.js:23 (anonymous function)

231
(function() {
	localStorage.getItem("eal-blacklisted-domains") === null
		? getDomains("eal")
		: checkIfDataIsRecent("eal");
	localStorage.getItem("iosiro-blacklisted-domains") === null
		? getDomains("iosiro")
		: checkIfDataIsRecent("iosiro");

	localStorage.getItem("409h-whitelisted-domains") === null
		? getDomains("409h")
		: checkIfDataIsRecent("409h");

	setInterval(function() {
		getDomains();
	}, 180000);

	chrome.tabs.query({ active: true, lastFocusedWindow: true }, function(tabs) {
		querycB(tabs);
	});

	chrome.tabs.onActivated.addListener(cb);
	chrome.tabs.onUpdated.addListener(cb);
})();

function cb() {
	chrome.tabs.query({ active: true, lastFocusedWindow: true }, function(tabs) {
		querycB(tabs);
	});
}

function querycB(tabs) {
	const SEARCH_STRING = ["myetherwallet"];
	const ealBlacklisted = JSON.parse(
		localStorage.getItem("eal-blacklisted-domains")
	);
	const iosiroBlacklisted = JSON.parse(
		localStorage.getItem("iosiro-blacklisted-domains")
	);

	const whitelisted = JSON.parse(
		localStorage.getItem("409h-whitelisted-domains")
	);

	const allDomains = ealBlacklisted.domains.concat(iosiroBlacklisted.domains);
	let urlRedirect;
	let foundWhitelist = whitelisted.domains.find(dom => {
		return dom === extractRootDomain(tabs[0].url);
	});

	let foundBlacklist = allDomains.find(dom => {
		return dom === extractRootDomain(tabs[0].url);
	});

**Comment by repsorp** [comment]
Not working here since v3.21.15
My last try...

**Comment by gamalielhere** [comment]
@repsorp can you try hard refreshing your browser?

**Comment by repsorp** [comment]
Don't know how to do this with Chromium...

Tried this:
Chrome: Quick hard refresh can be done by using the following short cut keys
Linux: Hold down Ctrl and click the Reload button. Or, Hold down Ctrl and press F5.

Didn't help, same issues

**Comment by gamalielhere** [comment]
@repsorp can you try updating your version to Version 68.0.3440.84 (Official Build) (64-bit)? I just tested there and it seems to work fine.

**Comment by repsorp** [comment]
This version is not available yet in my repo...

**Comment by repsorp** [comment]
I'll wait for this version to be available and I'll tell you then
Thanks for your help

**Comment by gamalielhere** [comment]
@repsorp If you can though, try using google chrome. Let me know how it goes!

**Comment by repsorp** [comment]
Didn't find 68.0.3440.84 (Official Build) (64-bit)
https://chromereleases.googleblog.com/2018/07/stable-channel-update-for-desktop.html
From a beta or dev channel ?

**Comment by gamalielhere** [comment]
@repsorp we actually just downloaded it from one of the app stores. But it looks like its from the stable channel. https://chromereleases.googleblog.com/2018/07/stable-channel-update-for-desktop_31.html

**Comment by repsorp** [comment]
chromium Version 68.0.3440.75
Everything running smoothly with v3.21.20
No more issues !
Big thanks
(didn't try with Chrome 68.0.3440.84, sorry)

**Comment by alonbg** [comment]
MacOS v10.13.4
Chrome version 70.0.3521.0 (Official Build) canary (64-bit)
Extension v3.21.20

When installing extension getting similar error (now  _domains_ , previously _url_)

fails on line
`const allDomains = ealBlacklisted.domains.concat(iosiroBlacklisted.domains);`

```
Error in response to tabs.query: TypeError: Cannot read property 'domains' of null
Context
_generated_background_page.html


Stack Trace
background/extension.js:44 (querycB)
background/extension.js:18 (Object.callback)
background/extension.js:17 (anonymous function)
background/extension.js:23 (anonymous function)


(function() {
	localStorage.getItem("eal-blacklisted-domains") === null
		? getDomains("eal")
		: checkIfDataIsRecent("eal");
	localStorage.getItem("iosiro-blacklisted-domains") === null
		? getDomains("iosiro")
		: checkIfDataIsRecent("iosiro");

	localStorage.getItem("409h-whitelisted-domains") === null
		? getDomains("409h")
		: checkIfDataIsRecent("409h");

	setInterval(function() {
		getDomains();
	}, 180000);

	chrome.tabs.query({ active: true, lastFocusedWindow: true }, function(tabs) {
		querycB(tabs);
	});

	chrome.tabs.onActivated.addListener(cb);
	chrome.tabs.onUpdated.addListener(cb);
})();

function cb() {
	chrome.tabs.query({ active: true, lastFocusedWindow: true }, function(tabs) {
		querycB(tabs);
	});
}

function querycB(tabs) {
	const SEARCH_STRING = ["myetherwallet"];
	const ealBlacklisted = JSON.parse(
		localStorage.getItem("eal-blacklisted-domains")
	);
	const iosiroBlacklisted = JSON.parse(
		localStorage.getItem("iosiro-blacklisted-domains")
	);

	const whitelisted = JSON.parse(
		localStorage.getItem("409h-whitelisted-domains")
	);

	const allDomains = ealBlacklisted.domains.concat(iosiroBlacklisted.domains);
	let urlRedirect;
	let foundWhitelist = whitelisted.domains.find(dom => {
		return dom === extractRootDomain(tabs[0].url);
	});
```

**Comment by gamalielhere** [comment]
@alonbg the url error occurs when the chrome tab doesn't have a url. It's usually when you're inspecting the background page for an extension. The other error seems to be inconsistent. I can't seem to replicate it. Let me know if this helps.

**Comment by repsorp** [comment]
"unsafe:chrome-extension://cahmballlldlagcgabgajchbpgroepfd/cx-wallet.html#my-wallet" error message is back

chromium Version 69.0.3497.81
MEW 3.21.24

![capture du 2018-09-14 15-33-43](https://user-images.githubusercontent.com/6297032/45553450-36ae4180-b834-11e8-812f-3510bd3cfec2.png)

**Comment by gamalielhere** [comment]
@repsorp refreshing it should fix it. ~I'm also making a fix now.~ #2067 should fix this issue.

**Comment by repsorp** [comment]
@gamalielhere 
Refreshing didn't make it...
Still doesn't work here

**Comment by gamalielhere** [comment]
@repsorp can you redownload the extension folder?

**Comment by repsorp** [comment]
@gamalielhere
MEW 3.22 works flawless
Thanks
