### ISSUE TITLE
Trezor error : TypeError: The first argument must be one of type string, Buffer, ArrayBuffer, Array, or Array-like Object. Received type undefined

### ISSUE THREAD

**Issue by ghost** [kvhnuke/etherwallet#2104]
cc @gamalielhere @kvhnuke @SteveMieskoski 

![default](https://user-images.githubusercontent.com/39383087/47066451-20bfe200-d221-11e8-9344-91c5ff39583e.PNG)

Can't unlock trezor due to the bug

**Comment by prusnak** [comment]
reports here:

https://www.reddit.com/r/TREZOR/comments/9ow9t3/suddenly_mew_redirects_to/
https://www.reddit.com/r/TREZOR/comments/9ovd8w/typeerror_with_myetherwallet/
https://www.reddit.com/r/TREZOR/comments/9ox4os/no_addresses_to_choose_while_trying_to_connect_to/
https://www.reddit.com/r/TREZOR/comments/9owcul/help_cant_access_my_trezor_using_mew/
https://www.reddit.com/r/TREZOR/comments/9owcdm/no_export_public_key_pop_up_prompt_with_mew/

**Comment by prusnak** [comment]
This is caused by deploying CSP Content Security Policy to MEW website without noticing this will block inclusion of third-party scripts such as connect. You need to add connect.trezor.io to CSP trusted domains.

**Comment by gamalielhere** [comment]
@eosclassicteam @prusnak thanks for submitting. We're currently working on a fix.

**Comment by gamalielhere** [comment]
Should be fixed now. Please hard refresh your browsers if it still isn't fixed. Don't hesitate to reopen issue if it persists after a hard refresh.

**Comment by JoeMcCreary** [comment]
still having issue....

**Comment by gamalielhere** [comment]
@JoeMcCreary Have you tried hard refreshing your browser?

**Comment by JoeMcCreary** [comment]
yeah several times

**Comment by gamalielhere** [comment]
@JoeMcCreary What browser are you using?

**Comment by JoeMcCreary** [comment]
Chrome:  And by Hard Refresh do you mean clearing cache and completely closing out then reopening?

**Comment by JoeMcCreary** [comment]
inpage.js:1 ATTENTION: In an effort to improve user privacy, MetaMask will stop exposing user accounts to dapps by default beginning November 2nd, 2018. Dapps should call provider.enable() in order to view and use accounts. Please see https://bit.ly/2QQHXvF for complete information and up-to-date example code.
(anonymous) @ inpage.js:1
etherwallet-master.js:5235 SCANTR m/44'/60'/0'/0 Object
$scope.scanTrezor @ etherwallet-master.js:5235
etherwallet-master.js:144475 Refused to frame 'https://connect.trezor.io/' because it violates the following Content Security Policy directive: "default-src 'self'". Note that 'frame-src' was not explicitly set, so 'default-src' is used as a fallback.

etherwallet-master.js:144454 Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('https://connect.trezor.io') does not match the recipient window's origin ('null').
onLoad @ etherwallet-master.js:144454
etherwallet-master.js:80621 TypeError: Cannot set property 'type' of undefined
    at ChildScope.$scope.setHDWallet (etherwallet-master.js:5117)
    at fn (eval at compile (etherwallet-master.js:81446), <anonymous>:4:153)
    at callback (etherwallet-master.js:93709)
    at ChildScope.$eval (etherwallet-master.js:84372)
    at ChildScope.$apply (etherwallet-master.js:84471)
    at HTMLButtonElement.<anonymous> (etherwallet-master.js:93713)
    at defaultHandlerWrapper (etherwallet-master.js:69176)
    at HTMLButtonElement.eventHandler (etherwallet-master.js:69164)
(anonymous) @ etherwallet-master.js:80621
(anonymous) @ etherwallet-master.js:76977
$apply @ etherwallet-master.js:84476
(anonymous) @ etherwallet-master.js:93713
defaultHandlerWrapper @ etherwallet-master.js:69176
eventHandler @ etherwallet-master.js:69164

**Comment by gamalielhere** [comment]
@JoeMcCreary  Depends on your OS:
Mac - Command + Shift + R
Ubuntu & Windows - Control + F5

**Comment by JoeMcCreary** [comment]
I'm using windows 7 on this laptop. I've cleared Chrome cache and closed it out, Several times.

**Comment by lisyk** [comment]
it still doesn't work even after hard refresh. I am on Mac

**Comment by JoeMcCreary** [comment]
Anyway... good luck! I've got to head out. Thanks for responding... I'm sure you'll get it figured out. I'll try again later. Thanks

**Comment by sraufcvinga** [comment]
Hello, the same here for me. I tryed everything you suggest but still doesnt work. I think I should wait for a final fix from you guys. But its a very bad moment just right now for me. Hope you'll fix it soon.

**Comment by gamalielhere** [comment]
@sraufcvinga @lisyk @JoeMcCreary It should be fixed now once you do a hard refresh. Closing this issue once again.

**Comment by lisyk** [comment]
it works now on Firefox but still having the same issue on Chrome

**Comment by gamalielhere** [comment]
@lisyk can you refresh normally?

**Comment by JoeMcCreary** [comment]
Refreshed Chrome cache and even rebooted my laptop just grins.... Still getting the same two errors as earlier posted. 
-- Refused to frame 'https://connect.trezor.io/' because it violates the following Content Security Policy directive: "default-src 'self'". Note that 'frame-src' was not explicitly set, so 'default-src' is used as a fallback.
-- etherwallet-master.js:144454 Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('https://connect.trezor.io') does not match the recipient window's origin ('null').

**Comment by lisyk** [comment]
> @lisyk can you refresh normally?

nope still doesn't work

**Comment by lisyk** [comment]
@JoeMcCreary  did you try Firefox? it works now for me

**Comment by gamalielhere** [comment]
> nope still doesn't work  
  
I can't seem to replicate it anymore on chrome. I'll keep looking into it

**Comment by gamalielhere** [comment]
@lisyk @JoeMcCreary if you guys can, try hard refreshing and then normal refresh.

**Comment by JoeMcCreary** [comment]
@gamalielhere  Okay I opened the Developer Tools then right clicked on the Refresh button (up top of Chrome by URL box) and chose "Empty Cache and Hard Reload". Then closed the browser. Still didn't work. Then just decided to do that same thing several times in a row and if finally fixed the problem... man! it was really hanging on to that old data! lol So it's working now in Chrome. Thanks!

**Comment by gamalielhere** [comment]
Weird. But thanks for letting me know. I'll go ahead and close this again.

**Comment by lisyk** [comment]
@JoeMcCreary @gamalielhere  that's weird but it helped me too. also only after about 10 hard reloads in a row  it works now

**Comment by JoeMcCreary** [comment]
@lisyk  Yeah, great! Interesting how it takes so many tries to stick.

**Comment by gamalielhere** [comment]
I wonder how that is since we did purge our cache. Anyways, thanks again for helping debug @JoeMcCreary @lisyk
